config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'links#index'

  resources :links do
    resources :comments do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end  
  end  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
  
  acts_as_votable
end

app/models/link.rb
class Link < ActiveRecord::Base
    validates :url , presence: true , uniqueness: true
    
    belongs_to :user
    has_many :comments
    
    def self.search(search)
        
        if search
           @tosearch = search.strip
           where(["url LIKE ?","%#{@tosearch}%"])
        else
           all
        end       
    end    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :links  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    before_action :authenticate_user!
    
    def create
        @link = Link.find(params[:link_id])
        @comment = Comment.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id
        @comment.link_id = @link.id
        
        if @comment.save
            redirect_to link_path(@link)
        else
            render "new"
        end 
    end
    
    def destroy
        @link = Link.find(params[:link_id])
        @comment = @link.comments.find(params[:id])
        @comment.destroy
        
        redirect_to link_path(@link)
    end
    
    def upvote
        @link = Link.find(params[:link_id])
        @comment = @link.comments.find(params[:id])
        @comment.upvote_by current_user
        redirect_to :back
    end
    
    def downvote
        @link = Link.find(params[:link_id])
        @comment = @link.comments.find(params[:id])
        @comment.downvote_by current_user
        redirect_to :back
    end  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    
    before_action :set_link ,only: [:show , :edit, :update, :destroy]
    before_action :authenticate_user! , except: [:index,:show]
    
    
    def index
       @links = Link.search(params[:search])
    end
    
    def show
       @comments = Comment.where(link_id: @link).order(cached_votes_score: :desc)
       @starred = @comments.first
    end
    
    def new
       @link = current_user.links.new
    end
    
    def create
       
            # params[:links].each do |link_params|
            # @links = Link.new(link_params)
            #     if @links.save
            #         redirect_to root_path
            #     else
            #         render "new"
            #     end    
            # end
            
            params[:links].each do |my_params|
                current_user.links.create(link_params(my_params))
               
            end
            
            
            redirect_to root_path
            
            # if params.has_key?("puppy")
            #     Puppy.create(puppy_params(params["puppy"]))
            # else
            #     params["puppies"].each do |puppy|
            # if puppy["name"] != "" || puppy["breed"] != ""
            #     Puppy.create(puppy_params(puppy))
            # end
            # end
            # end
    end
    
    def edit
        
    end
    
    def update
        if @link.update(link_params)
            redirect_to root_path
        else
            render "edit"
        end    
            
    end
    
    def destroy
        @link.destroy
        redirect_to root_path
    end    
       
    private
    
    def set_link
       @link =  Link.find(params[:id]) 
    end  
    
    def link_params(my_params)
        my_params.permit(:url)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
    def embed(youtube_url)
        youtube_id = youtube_url.split("=").last
        content_tag(:iframe, nil,width: 480 , height: 360 , src: "//www.youtube.com/embed/#{youtube_id}")
    end
    
    def thumbnail(youtube_url)
        youtube_id = youtube_url.split("=").last
        
        image_tag("https://img.youtube.com/vi/#{youtube_id}/hqdefault.jpg" , size: "250x200")
    end 
    
    def name(youtube_url)
        video = VideoInfo.new(youtube_url)
        video.title.truncate(35)
        
        
    end    
end

app/views/comments/_form.html.erb
<%= form_for([@link , @link.comments.build] ,class:"form-group" )  do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content ,class:"form-control" , size: "100*100" %>
    <br/>
    <%= f.button :submit , class:"btb btn-primary" %>
<% end %>    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ctc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" rel="stylesheet"></link>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"></link>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
      <%= link_to "SlimDown" , root_path , class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home" , root_path %></li>
        <li><%= link_to "Post Links" , new_link_path %></li>
        
      </ul>
      
     

      <%= form_tag(links_path, method: 'get', class: "navbar-form navbar-left") do %>
          <%= text_field_tag :search, params[:search], class: "form-control" , placeholder: "Enter URL to Search for"  %>
          <%= submit_tag "Search" , class: "btn btn-default" %>
      <% end %>

      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            
            <li><%= link_to edit_user_registration_path do  %>
                <i class="glyphicon glyphicon-user"></i> Account Settings
                <% end %>
            </li>
            <li><%= link_to destroy_user_session_path , method: :delete , data: {confirm: "Wanna Log out ?"} do  %>
                <i class="glyphicon glyphicon-log-out"></i> Sign Out
                <% end %>
            </li>
            
            
        <% else %>
            <li><%= link_to new_user_registration_path do  %>
                <i class="glyphicon glyphicon-user"></i> Sign Up
                <% end %>
            </li>
            <li><%= link_to user_session_path do %>
                <i class="glyphicon glyphicon-log-in"> LogIn</i>
                <% end %>
            </li>
        
        <% end %>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid">
  <% flash.each do |name , msg| %>
    <% content_tag :div , msg , class: "alert alert-info" %>
  <% end %> 
  
</div>  

<div class="wrapper">
  <%= yield %>
</div>


</body>
</html>

app/views/links/_form.html.erb
<!--<%= form_for @link do |f| %>-->
<!--    <% if @link.errors.any? %>-->
<!--        <ul>-->
<!--           <%= @link.errors.full_messages.each do |msg| %>-->
<!--                <li><%= msg %></li>-->
<!--            <% end %>    -->
<!--        </ul>-->
<!--    <% end %>  -->
<!--    <p>-->
<!--        <%= f.label :url %>-->
<!--        <%= f.text_field :url %>-->
<!--    </p>-->
<!--    <p>-->
<!--        <%= f.submit %>-->
<!--    </p>-->
<!--<% end %>    -->

<%= form_tag @link , class: "form-group" do %>
  <% 4.times do |i|%>
    URL : <%= text_field_tag :url, "", :name => "links[][url]" , class: "form-control" %>
    <br/>
    <hr>
  <% end %>
  <%= submit_tag "Submit" , class: "btn btn-default"%>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Links</h1>

<%= render "form" %>

<%= link_to "Home" , root_path %>

app/views/links/index.html.erb
<h1 align="center">Reviewed Links !</h1>

<% if @links.empty? %>
    <h1>Oops , No Links to be found ! Would you like to <%= link_to "post some" , new_link_path %> </h1>
<% else %>    
<div id="posts">
    <% @links.each do |link| %>
    <div class="post">
        <div class="post_image">
            <%= link_to thumbnail(link.url) , link %>
        </div>
        <div class="post_content">
            <br/>
            <div class="title">
             <%= link_to name(link.url) , link %>
            <br/>  
            </div>
            
        </div>
        
    </div>
    <% end %>
</div>
<% end %>

app/views/links/new.html.erb
<h1>Enter The Video URLs !</h1>

<%= render "form" %>

app/views/links/show.html.erb
<div class="row">
    <div class="col-lg-6">
        <%= embed(@link.url) %><br/>
       
    </div>
    <div class="col-lg-6">
        <div class="description">
            <% if @comments.any? %>
                <h3 id="description_head">Video Description :</h3>
                <%= simple_format(@starred.content) %>
            <% end %>  
        </div>
    </div>
</div>




  

<hr>
<div id="comments"> 
    <h2 class="comment_count">
        <i class="fa fa-comments-o"></i>
        <%= pluralize(@link.comments.count , "Comment") %></h2>
    <% @comments.each do |comment| %>
    <div class="comment">
        <p class="username">
            <%= comment.user.email %> Says , 
        </p>
        <p class="content">
             <%= comment.content %>
        </p>
        
       
        <%= link_to like_link_comment_path(@link.id,comment) , method: :put do %>
        <i class="fa fa-thumbs-o-up"></i>
        <%= pluralize(comment.get_upvotes.size, " Like") %>
        <% end %> 
        <%= link_to dislike_link_comment_path(@link.id,comment) , method: :put do %>
        <i class="fa fa-thumbs-o-down"></i>
        <%= pluralize(comment.get_upvotes.size, " Dislike") %>
        <% end %>
        <%= link_to [@link , comment] , method: :delete do %>
        <i class="fa fa-trash"> Delete</i>
        <% end %>
    <br/>
        
    </div>
    <% end %>
<br/>
    <%= render "comments/form" %>
</div>